set(_CATKIN_CURRENT_PACKAGE "kursant1_setup_tf")
set(kursant1_setup_tf_VERSION "0.0.0")
set(kursant1_setup_tf_MAINTAINER "edward <edward@todo.todo>")
set(kursant1_setup_tf_PACKAGE_FORMAT "1")
set(kursant1_setup_tf_BUILD_DEPENDS "geometry_msgs" "roscpp" "tf")
set(kursant1_setup_tf_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "tf")
set(kursant1_setup_tf_BUILDTOOL_DEPENDS "catkin")
set(kursant1_setup_tf_BUILDTOOL_EXPORT_DEPENDS )
set(kursant1_setup_tf_EXEC_DEPENDS "geometry_msgs" "roscpp" "tf")
set(kursant1_setup_tf_RUN_DEPENDS "geometry_msgs" "roscpp" "tf")
set(kursant1_setup_tf_TEST_DEPENDS )
set(kursant1_setup_tf_DOC_DEPENDS )
set(kursant1_setup_tf_DEPRECATED "")